export interface ChallengeInstance {
    id: string;
    title: string;
    description: string;
    difficulty: 'Easy' | 'Normal' | 'Hard' | 'Epic';
    recommendedLevel: number;
    rewards: string[];
}

export interface ChallengeCatalog {
    dungeons: ChallengeInstance[];
    raids: ChallengeInstance[];
    trials: ChallengeInstance[];
}

const createChallengeCatalog = (): ChallengeCatalog => ({
    dungeons: [
        { id: 'dungeon-01', title: 'Ashen Catacombs', description: 'A winding crypt where the dead whisper names.', difficulty: 'Easy', recommendedLevel: 3, rewards: ['Herb Bundle', 'Copper Coin'] },
        { id: 'dungeon-02', title: 'Mire Hollow', description: 'A marshy maze crowded with creeping monsters.', difficulty: 'Easy', recommendedLevel: 5, rewards: ['Mire Key', 'Potion'] },
        { id: 'dungeon-03', title: 'Frostbound Grotto', description: 'An ice-choked cavern of shifting walls.', difficulty: 'Normal', recommendedLevel: 8, rewards: ['Frost Shard', 'Warm Cloak'] },
        { id: 'dungeon-04', title: 'Cinder Keep', description: 'A fortress of flame and fallen banners.', difficulty: 'Normal', recommendedLevel: 10, rewards: ['Fire Ember', 'Iron Ring'] },
        { id: 'dungeon-05', title: 'Sunken Reliquary', description: 'Ancient halls swallowed by dark water.', difficulty: 'Hard', recommendedLevel: 14, rewards: ['Aqua Pearl', 'Mystic Relic'] },
        { id: 'dungeon-06', title: 'Moonlit Maw', description: 'A cavern where moonlight turns every shadow hostile.', difficulty: 'Hard', recommendedLevel: 18, rewards: ['Moonstone', 'Silver Dagger'] },
        { id: 'dungeon-07', title: 'Stormspire Vault', description: 'A vertical dungeon coursing with lightning.', difficulty: 'Epic', recommendedLevel: 22, rewards: ['Storm Core', 'Thunder Gauntlets'] },
        { id: 'dungeon-08', title: 'Eclipse Citadel', description: 'The fortress of endless night and ruined kings.', difficulty: 'Epic', recommendedLevel: 26, rewards: ['Eclipse Sigil', 'Royal Crown'] },
        { id: 'dungeon-09', title: 'Verdant Labyrinth', description: 'Tangled roots conceal ancient mechanisms.', difficulty: 'Normal', recommendedLevel: 12, rewards: ['Wildvine', 'Compass'] },
        { id: 'dungeon-10', title: 'Ruinous Archive', description: 'A library of shattered tomes and whispering spirits.', difficulty: 'Hard', recommendedLevel: 17, rewards: ['Archive Key', 'Spellbook'] },
        { id: 'dungeon-11', title: 'Tyrant Stair', description: 'A stairway that descends into old war memories.', difficulty: 'Hard', recommendedLevel: 20, rewards: ['War Badge', 'Chainmail'] },
        { id: 'dungeon-12', title: 'Dread Basin', description: 'A crater lake of black water and pale bones.', difficulty: 'Epic', recommendedLevel: 24, rewards: ['Bone Charm', 'Obsidian Ore'] },
        { id: 'dungeon-13', title: 'Forgotten Forge', description: 'An abandoned forge where the metal still remembers.', difficulty: 'Normal', recommendedLevel: 11, rewards: ['Hammer', 'Smelted Steel'] },
        { id: 'dungeon-14', title: 'Thornwatch Keep', description: 'A watchtower overrun by thorn-wreathed monsters.', difficulty: 'Normal', recommendedLevel: 13, rewards: ['Rose Thorn', 'Defender Shield'] },
        { id: 'dungeon-15', title: 'Galebreaker Pass', description: 'A mountain pass where the winds seek blood.', difficulty: 'Hard', recommendedLevel: 19, rewards: ['Stormproof Cloak', 'Wind Rune'] },
        { id: 'dungeon-16', title: 'Bloodroot Chapel', description: 'A desecrated chapel haunted by old vows.', difficulty: 'Hard', recommendedLevel: 21, rewards: ['Bloodroot', 'Ceremonial Dagger'] },
        { id: 'dungeon-17', title: 'Sable Barracks', description: 'War rooms rotting under a veil of ash.', difficulty: 'Epic', recommendedLevel: 25, rewards: ['Sable Banner', 'Guardian Helm'] },
        { id: 'dungeon-18', title: 'Wyrm Nest', description: 'A dragon-broken cavern of scales and smoke.', difficulty: 'Epic', recommendedLevel: 28, rewards: ['Wyrm Scale', 'Dragon Tooth'] },
        { id: 'dungeon-19', title: 'Shattered Monastery', description: 'A monastery of broken bells and fading prayers.', difficulty: 'Normal', recommendedLevel: 15, rewards: ['Prayer Bead', 'Monk Robe'] },
        { id: 'dungeon-20', title: 'Furnace Hollow', description: 'A fiery ravine that devours the unwary.', difficulty: 'Hard', recommendedLevel: 23, rewards: ['Ash Token', 'Flameproof Boots'] },
        { id: 'dungeon-21', title: 'Mirror Maze', description: 'Hallways that twist with every step.', difficulty: 'Easy', recommendedLevel: 6, rewards: ['Mirror Shard', 'Potion'] },
        { id: 'dungeon-22', title: 'Raven Fen', description: 'A misty bog where ravens patrol the reeds.', difficulty: 'Easy', recommendedLevel: 7, rewards: ['Feather Charm', 'Antidote'] },
        { id: 'dungeon-23', title: 'Stonewake Tomb', description: 'Tombs that reopen whenever a bell rings.', difficulty: 'Normal', recommendedLevel: 9, rewards: ['Bone Key', 'Lantern'] },
        { id: 'dungeon-24', title: 'Emberwood Den', description: 'A forest dungeon of molten roots and ash.', difficulty: 'Normal', recommendedLevel: 12, rewards: ['Emberwood', 'Scout Knife'] },
        { id: 'dungeon-25', title: 'Graveglass Cavern', description: 'A cavern full of luminous skulls and glass shards.', difficulty: 'Hard', recommendedLevel: 16, rewards: ['Graveglass', 'Soul Lantern'] },
        { id: 'dungeon-26', title: 'Iron Choir', description: 'A hall where warped machinery hums like a choir.', difficulty: 'Hard', recommendedLevel: 18, rewards: ['Iron Note', 'Mechanic Gauntlet'] },
        { id: 'dungeon-27', title: 'Dusk Reservoir', description: 'A reservoir of dark water guarded by ancient wards.', difficulty: 'Epic', recommendedLevel: 26, rewards: ['Reservoir Core', 'Dusk Ring'] },
        { id: 'dungeon-28', title: 'Starfall Spire', description: 'A spire whose summit touches the heavens.', difficulty: 'Epic', recommendedLevel: 30, rewards: ['Starfall Fragment', 'Halo Crown'] },
        { id: 'dungeon-29', title: 'Mourning Quay', description: 'Harbor ruins filled with fog and wreckage.', difficulty: 'Normal', recommendedLevel: 14, rewards: ['Harbor Map', 'Salted Rations'] },
        { id: 'dungeon-30', title: 'Blight Orchard', description: 'Fruit trees that grow with poisoned light.', difficulty: 'Hard', recommendedLevel: 21, rewards: ['Blight Fruit', 'Orchard Key'] },
        { id: 'dungeon-31', title: 'Cauterized Wells', description: 'A maze of wells where heat rises from below.', difficulty: 'Easy', recommendedLevel: 4, rewards: ['Wellstone', 'Healing Salve'] },
        { id: 'dungeon-32', title: 'Rusted Gateway', description: 'A broken gate into a forgotten warzone.', difficulty: 'Normal', recommendedLevel: 11, rewards: ['Rust Key', 'Battle Medallion'] },
        { id: 'dungeon-33', title: 'Fangspire Hollow', description: 'A canyon hideout of hooked beasts and echoes.', difficulty: 'Hard', recommendedLevel: 17, rewards: ['Fangscale', 'Hunter Bow'] },
        { id: 'dungeon-34', title: 'Hollowed Court', description: 'A court ruled by stolen crowns and empty thrones.', difficulty: 'Hard', recommendedLevel: 20, rewards: ['Court Seal', 'Royal Mantle'] },
        { id: 'dungeon-35', title: 'Draught of Sorrows', description: 'A poisoned cellar of memory and mildew.', difficulty: 'Epic', recommendedLevel: 27, rewards: ['Sorrow Vial', 'Spellglass'] },
        { id: 'dungeon-36', title: 'Ivory Sepulcher', description: 'A sepulcher lit by pale, holy light.', difficulty: 'Epic', recommendedLevel: 29, rewards: ['Ivory Relic', 'Holy Sigil'] },
        { id: 'dungeon-37', title: 'Gloomwater Cavern', description: 'A cavern whose waters reflect the future.', difficulty: 'Normal', recommendedLevel: 10, rewards: ['Future Pearl', 'Water Rune'] },
        { id: 'dungeon-38', title: 'Gilded Maw', description: 'A serpent-like tunnel lined with gold.', difficulty: 'Hard', recommendedLevel: 22, rewards: ['Gold Teeth', 'Treasure Map'] },
        { id: 'dungeon-39', title: 'Abyssal Chapel', description: 'A chapel where fissures open into the void.', difficulty: 'Epic', recommendedLevel: 31, rewards: ['Abyssal Ink', 'Void Mantle'] },
        { id: 'dungeon-40', title: 'Dragonwake Vault', description: 'A vault beneath old mountains where dragons once slept.', difficulty: 'Epic', recommendedLevel: 35, rewards: ['Dragonwake Key', 'Legendary Scale'] },
    ],
    raids: [
        { id: 'raid-01', title: 'Raid on Blackbarrow', description: 'A bandit encampment turned into a war zone.', difficulty: 'Easy', recommendedLevel: 8, rewards: ['Bandit Crest', 'Shortbow'] },
        { id: 'raid-02', title: 'Skullwatch Siege', description: 'Defend the wall while the dead assault the gate.', difficulty: 'Easy', recommendedLevel: 10, rewards: ['Siege Banner', 'Shield Charm'] },
        { id: 'raid-03', title: 'Temple of the Third Flame', description: 'A raid against fire-cultists in a ruined shrine.', difficulty: 'Normal', recommendedLevel: 13, rewards: ['Flame Idol', 'Prayer Ring'] },
        { id: 'raid-04', title: 'Glaive Harbor Assault', description: 'A fleet raid on a pirate stronghold.', difficulty: 'Normal', recommendedLevel: 15, rewards: ['Harbor Compass', 'Glaive'] },
        { id: 'raid-05', title: 'Citadel of the Hollow King', description: 'Assault a fortress ruled by a false monarch.', difficulty: 'Hard', recommendedLevel: 18, rewards: ['Crown Fragment', 'Royal Spear'] },
        { id: 'raid-06', title: 'Night Ferry Ambush', description: 'Secure a ferry carrying relics through stormy waters.', difficulty: 'Hard', recommendedLevel: 20, rewards: ['Ferry Token', 'Stormblade'] },
        { id: 'raid-07', title: 'The Wyrm Breakers', description: 'A raid on a dragon cult’s hidden base.', difficulty: 'Epic', recommendedLevel: 24, rewards: ['Wyrm Sigil', 'Dragonscale Armor'] },
        { id: 'raid-08', title: 'Skybridge Overrun', description: 'Hold a skybridge while the enemy pours through.', difficulty: 'Epic', recommendedLevel: 26, rewards: ['Skyhook', 'Aether Cloak'] },
        { id: 'raid-09', title: 'Mothlight Bastion', description: 'An assault on a luminous fortress in the fog.', difficulty: 'Normal', recommendedLevel: 12, rewards: ['Moth Dust', 'Bastion Key'] },
        { id: 'raid-10', title: 'Frostgate Siege', description: 'A siege battle in a mountain gatehouse.', difficulty: 'Hard', recommendedLevel: 19, rewards: ['Frostgate Rune', 'Iceblade'] },
        { id: 'raid-11', title: 'Ashen Caravan', description: 'Protect merchants from raiders in a burning pass.', difficulty: 'Easy', recommendedLevel: 9, rewards: ['Caravan Token', 'Leather Satchel'] },
        { id: 'raid-12', title: 'Ruinwatch Stronghold', description: 'Storm a keep full of war machines and traps.', difficulty: 'Hard', recommendedLevel: 21, rewards: ['Watch Key', 'Runic Shield'] },
        { id: 'raid-13', title: 'Dreadwake Port', description: 'The harbor of ghosts and black sails.', difficulty: 'Epic', recommendedLevel: 27, rewards: ['Dreadwake Lantern', 'Ghost Net'] },
        { id: 'raid-14', title: 'Sunfire Bastion', description: 'A blazing fortress at the edge of the desert.', difficulty: 'Normal', recommendedLevel: 16, rewards: ['Sunfire Pearl', 'Sunshield'] },
        { id: 'raid-15', title: 'Ravenhold Reprise', description: 'Retake a mountain hold from raven cultists.', difficulty: 'Hard', recommendedLevel: 22, rewards: ['Raven Claw', 'Mountain Axe'] },
        { id: 'raid-16', title: 'Shattered Veil', description: 'Break through a barrier that masks a hidden city.', difficulty: 'Epic', recommendedLevel: 29, rewards: ['Veil Shard', 'Aether Crown'] },
        { id: 'raid-17', title: 'Ironwake Crossing', description: 'A battle over a bridge of iron and sparks.', difficulty: 'Normal', recommendedLevel: 14, rewards: ['Ironwake Badge', 'Crossbow'] },
        { id: 'raid-18', title: 'Tombbreaker Camp', description: 'Strike a necromancer camp beneath the hills.', difficulty: 'Hard', recommendedLevel: 20, rewards: ['Breaker Token', 'Bonebreaker'] },
        { id: 'raid-19', title: 'Moonwell Outpost', description: 'Defend a moonlit outpost from monstrous incursion.', difficulty: 'Hard', recommendedLevel: 23, rewards: ['Moonwell Talisman', 'Spear of Dawn'] },
        { id: 'raid-20', title: 'The Hollow Fleet', description: 'Board a ghost fleet under the black sea.', difficulty: 'Epic', recommendedLevel: 30, rewards: ['Black Sail', 'Sea Rune'] },
        { id: 'raid-21', title: 'Whispergate', description: 'Storm a frontier gate where whispers become commands.', difficulty: 'Easy', recommendedLevel: 7, rewards: ['Whisper Key', 'Travel Boots'] },
        { id: 'raid-22', title: 'Red Ember Ridge', description: 'A ridge battle fought in cinders and smoke.', difficulty: 'Normal', recommendedLevel: 11, rewards: ['Ember Token', 'Ridge Helm'] },
        { id: 'raid-23', title: 'Sable Quarry', description: 'The quarry of old giants and broken carts.', difficulty: 'Normal', recommendedLevel: 13, rewards: ['Sable Stone', 'Pickaxe'] },
        { id: 'raid-24', title: 'Cairnwatch', description: 'Protect a cairn from the dead who seek its treasure.', difficulty: 'Hard', recommendedLevel: 18, rewards: ['Cairn Rune', 'Lantern of Vigil'] },
        { id: 'raid-25', title: 'Sunken Armada', description: 'The remains of a fallen fleet rise from the bay.', difficulty: 'Hard', recommendedLevel: 24, rewards: ['Armada Coin', 'Anchor Spear'] },
        { id: 'raid-26', title: 'Stormcaller Tower', description: 'A tower siege under a storm that never breaks.', difficulty: 'Epic', recommendedLevel: 28, rewards: ['Stormcaller Gem', 'Thunder Rod'] },
        { id: 'raid-27', title: 'Miregate Fort', description: 'A marsh fort where every wall is slick with rot.', difficulty: 'Normal', recommendedLevel: 15, rewards: ['Miregate Seal', 'Bogblade'] },
        { id: 'raid-28', title: 'Cinderfall Keep', description: 'A stronghold that erupts in lava and ash.', difficulty: 'Hard', recommendedLevel: 21, rewards: ['Cinderfall Crest', 'Lava Shield'] },
        { id: 'raid-29', title: 'Voidmarket Raid', description: 'A raid on a market that trades in dark relics.', difficulty: 'Epic', recommendedLevel: 31, rewards: ['Void Coin', 'Shadow Ledger'] },
        { id: 'raid-30', title: 'Gilded Throne', description: 'Take the throne room from the false king.', difficulty: 'Epic', recommendedLevel: 34, rewards: ['Throne Key', 'Golden Scepter'] },
        { id: 'raid-31', title: 'Ridge of Echoes', description: 'The hillside path where old soldiers still fight.', difficulty: 'Easy', recommendedLevel: 6, rewards: ['Echo Bell', 'Travel Cloak'] },
        { id: 'raid-32', title: 'Brimstone Gate', description: 'A gate of lava and iron where the earth trembles.', difficulty: 'Normal', recommendedLevel: 12, rewards: ['Brimstone Key', 'Fireproof Helm'] },
        { id: 'raid-33', title: 'Spear of the Dawn', description: 'A raid to claim a relic from a sunrise temple.', difficulty: 'Hard', recommendedLevel: 17, rewards: ['Dawn Spear', 'Holy Banner'] },
        { id: 'raid-34', title: 'Vault of Thorns', description: 'A fortified vault guarded by thorn-bound sentries.', difficulty: 'Hard', recommendedLevel: 22, rewards: ['Thorn Seal', 'Vineblade'] },
        { id: 'raid-35', title: 'Hearthless Keep', description: 'A keep of empty hearths and frozen banners.', difficulty: 'Epic', recommendedLevel: 28, rewards: ['Hearthstone', 'Frostguard'] },
        { id: 'raid-36', title: 'Demonwake Harbor', description: 'A harbor raid against ships carrying infernal cargo.', difficulty: 'Epic', recommendedLevel: 33, rewards: ['Demonwake Compass', 'Infernal Hook'] },
        { id: 'raid-37', title: 'Mournspire Citadel', description: 'An assault on a citadel lit by mourning lamps.', difficulty: 'Normal', recommendedLevel: 16, rewards: ['Mournspire Sigil', 'Blackmail Blade'] },
        { id: 'raid-38', title: 'Tidal Skull Fort', description: 'A fort overrun by sea and skeletons.', difficulty: 'Hard', recommendedLevel: 23, rewards: ['Skull Anchor', 'Tidal Axe'] },
        { id: 'raid-39', title: 'Starfang Bastion', description: 'A fortress laid out in a star-shaped array.', difficulty: 'Epic', recommendedLevel: 32, rewards: ['Starfang Shard', 'Astral Blade'] },
        { id: 'raid-40', title: 'The Last Crown', description: 'The final raid for a crown that bends the battlefield.', difficulty: 'Epic', recommendedLevel: 36, rewards: ['Last Crown', 'Imperial Crest'] },
    ],
    trials: [
        { id: 'trial-01', title: 'Trial of the First Step', description: 'A beginner test of endurance and grit.', difficulty: 'Easy', recommendedLevel: 2, rewards: ['Training Medal', 'Starter Herb'] },
        { id: 'trial-02', title: 'Trial of the Lantern', description: 'Light the path without losing your nerve.', difficulty: 'Easy', recommendedLevel: 3, rewards: ['Lantern Shard', 'Potion'] },
        { id: 'trial-03', title: 'Trial of the River', description: 'Cross a current of flowing stone and fire.', difficulty: 'Easy', recommendedLevel: 4, rewards: ['River Token', 'Bandage'] },
        { id: 'trial-04', title: 'Trial of the Ashen Wind', description: 'Resist the gusts that strip the flesh from bone.', difficulty: 'Normal', recommendedLevel: 6, rewards: ['Ash Token', 'Travel Ration'] },
        { id: 'trial-05', title: 'Trial of the Silent Bell', description: 'A chamber where sound itself is a hazard.', difficulty: 'Normal', recommendedLevel: 7, rewards: ['Bell Clapper', 'Antidote'] },
        { id: 'trial-06', title: 'Trial of the Frost Veil', description: 'Walk an icy gate without losing your footing.', difficulty: 'Normal', recommendedLevel: 8, rewards: ['Frost Token', 'Warm Mantle'] },
        { id: 'trial-07', title: 'Trial of the Thorn Crown', description: 'Pass through a garden of living thorns.', difficulty: 'Hard', recommendedLevel: 9, rewards: ['Thorn Crown', 'Guard Charm'] },
        { id: 'trial-08', title: 'Trial of the Moonwell', description: 'Reclaim a relic from a basin of moonlight.', difficulty: 'Hard', recommendedLevel: 10, rewards: ['Moonwell Token', 'Moon Charm'] },
        { id: 'trial-09', title: 'Trial of the Ember Gate', description: 'Pass through a fire gate while the heat rises.', difficulty: 'Hard', recommendedLevel: 11, rewards: ['Ember Seal', 'Flame Cloak'] },
        { id: 'trial-10', title: 'Trial of the Broken Sword', description: 'Restore honor to a ruined blade.', difficulty: 'Epic', recommendedLevel: 12, rewards: ['Blade Shard', 'Heroic Medal'] },
        { id: 'trial-11', title: 'Trial of the Hollow Heart', description: 'Face the emptiness without surrendering hope.', difficulty: 'Epic', recommendedLevel: 13, rewards: ['Heart Key', 'Soul Gem'] },
        { id: 'trial-12', title: 'Trial of the Red Path', description: 'Take the blood-marked road to truth.', difficulty: 'Normal', recommendedLevel: 5, rewards: ['Red Thread', 'Minor Potion'] },
        { id: 'trial-13', title: 'Trial of the Stone Mask', description: 'Unmask the ancient guardian beneath the cliff.', difficulty: 'Normal', recommendedLevel: 8, rewards: ['Mask Fragment', 'Stone Charm'] },
        { id: 'trial-14', title: 'Trial of the Iron Lattice', description: 'Solve a maze of moving iron bars.', difficulty: 'Hard', recommendedLevel: 10, rewards: ['Lattice Key', 'Iron Ring'] },
        { id: 'trial-15', title: 'Trial of the Black Tide', description: 'Endure a tide that consumes every sound.', difficulty: 'Hard', recommendedLevel: 12, rewards: ['Tide Token', 'Black Pearl'] },
        { id: 'trial-16', title: 'Trial of the Golden Echo', description: 'Hear the echo that reveals hidden doors.', difficulty: 'Epic', recommendedLevel: 14, rewards: ['Echo Coin', 'Golden Sigil'] },
        { id: 'trial-17', title: 'Trial of the Drowned Crown', description: 'Retrieve a crown from a pool of ancient grief.', difficulty: 'Epic', recommendedLevel: 15, rewards: ['Crown Piece', 'Tide Crown'] },
        { id: 'trial-18', title: 'Trial of the Vengeful Star', description: 'Face a star that falls and remembers.', difficulty: 'Normal', recommendedLevel: 9, rewards: ['Star Ash', 'Star Pendant'] },
        { id: 'trial-19', title: 'Trial of the Sable Mirror', description: 'Confront your reflection and survive the answer.', difficulty: 'Hard', recommendedLevel: 11, rewards: ['Mirror Dust', 'Shadow Cloak'] },
        { id: 'trial-20', title: 'Trial of the Fifth Door', description: 'Work through a door that opens only in sequence.', difficulty: 'Hard', recommendedLevel: 13, rewards: ['Door Key', 'Rune Token'] },
        { id: 'trial-21', title: 'Trial of the Glass Serpent', description: 'Move through an arena of shattering reflections.', difficulty: 'Epic', recommendedLevel: 16, rewards: ['Glass Scale', 'Serpent Brooch'] },
        { id: 'trial-22', title: 'Trial of the Burning Choir', description: 'Sing through the fire without losing your breath.', difficulty: 'Epic', recommendedLevel: 17, rewards: ['Choir Note', 'Phoenix Feather'] },
        { id: 'trial-23', title: 'Trial of the Hollow Moon', description: 'Cross a hall where the moon is a weapon.', difficulty: 'Normal', recommendedLevel: 7, rewards: ['Moon Dust', 'Moonstone'] },
        { id: 'trial-24', title: 'Trial of the Blood Orchard', description: 'Harvest from a grove that drinks the living.', difficulty: 'Hard', recommendedLevel: 10, rewards: ['Blood Fruit', 'Orchard Charm'] },
        { id: 'trial-25', title: 'Trial of the Grave Lantern', description: 'A trial where every lantern reveals a different fear.', difficulty: 'Hard', recommendedLevel: 12, rewards: ['Lantern Flame', 'Grave Candle'] },
        { id: 'trial-26', title: 'Trial of the Cinder Thread', description: 'Follow a thread that leads through flame.', difficulty: 'Epic', recommendedLevel: 15, rewards: ['Thread of Flame', 'Cinder Ring'] },
        { id: 'trial-27', title: 'Trial of the Storm Choir', description: 'Face a storm that sings with old voices.', difficulty: 'Epic', recommendedLevel: 18, rewards: ['Thunder Note', 'Storm Vow'] },
        { id: 'trial-28', title: 'Trial of the Sunken Gate', description: 'Open the gate beneath a flooded ruin.', difficulty: 'Normal', recommendedLevel: 8, rewards: ['Gate Key', 'Aqua Charm'] },
        { id: 'trial-29', title: 'Trial of the Iron Hand', description: 'A trial of strength, discipline, and discipline.', difficulty: 'Hard', recommendedLevel: 11, rewards: ['Iron Hand', 'Battle Token'] },
        { id: 'trial-30', title: 'Trial of the White Ash', description: 'Cross a field of ash that remembers every footstep.', difficulty: 'Hard', recommendedLevel: 13, rewards: ['White Ash', 'Ashen Medal'] },
        { id: 'trial-31', title: 'Trial of the Blue Flame', description: 'A trial of calm amid the inferno.', difficulty: 'Epic', recommendedLevel: 16, rewards: ['Blue Flame', 'Azure Ring'] },
        { id: 'trial-32', title: 'Trial of the Hollow Crown', description: 'A trial of pride and the cost of power.', difficulty: 'Epic', recommendedLevel: 18, rewards: ['Crown Fragment', 'Royal Seal'] },
        { id: 'trial-33', title: 'Trial of the Gilded Vine', description: 'Climb through a vine-wrapped tower of gold.', difficulty: 'Normal', recommendedLevel: 9, rewards: ['Golden Vine', 'Vine Charm'] },
        { id: 'trial-34', title: 'Trial of the Stormwake', description: 'Survive a room that awakens with every thunderclap.', difficulty: 'Hard', recommendedLevel: 12, rewards: ['Stormwake Token', 'Thunder Charm'] },
        { id: 'trial-35', title: 'Trial of the Warden Eye', description: 'A test of attention, memory, and patience.', difficulty: 'Hard', recommendedLevel: 14, rewards: ['Warden Eye', 'Silver Sigil'] },
        { id: 'trial-36', title: 'Trial of the Obsidian Gate', description: 'Break through a gate that only yields to the worthy.', difficulty: 'Epic', recommendedLevel: 17, rewards: ['Obsidian Key', 'Void Badge'] },
        { id: 'trial-37', title: 'Trial of the Drowned Rose', description: 'An aquatic garden of petals and drowned statues.', difficulty: 'Normal', recommendedLevel: 8, rewards: ['Rose Petal', 'Water Crest'] },
        { id: 'trial-38', title: 'Trial of the Ember Crown', description: 'A trial crowned in fire and forgotten glory.', difficulty: 'Hard', recommendedLevel: 13, rewards: ['Ember Crown', 'Crown Token'] },
        { id: 'trial-39', title: 'Trial of the Black Star', description: 'A trial where the sky itself turns hostile.', difficulty: 'Epic', recommendedLevel: 20, rewards: ['Black Star', 'Astral Charm'] },
        { id: 'trial-40', title: 'Trial of the Last Dawn', description: 'The final trial, where dawn breaks over the dead.', difficulty: 'Epic', recommendedLevel: 22, rewards: ['Last Dawn', 'Legendary Crest'] },
    ],
});

export const getChallengeCatalog = (): ChallengeCatalog => createChallengeCatalog();
export const getDungeons = (): ChallengeInstance[] => getChallengeCatalog().dungeons;
export const getRaids = (): ChallengeInstance[] => getChallengeCatalog().raids;
export const getTrials = (): ChallengeInstance[] => getChallengeCatalog().trials;
