export interface AssetDefinition {
    kind: 'image' | 'json' | 'sound' | 'tmx-map' | 'sprite-sheet' | 'canvas';
    key: string;
    path: string;
    options?: Record<string, unknown>;
}

export interface AssetDatabaseConfig {
    assets: AssetDefinition[];
}

export const createDefaultAssetDatabaseConfig = (): AssetDatabaseConfig => ({
    assets: [
        { kind: 'image', key: 'title', path: 'res/title.png' },
        { kind: 'sprite-sheet', key: 'hero', path: 'res/hero.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-male', path: 'res/hero-male.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-female', path: 'res/hero-female.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-warrior', path: 'res/hero-warrior.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-mage', path: 'res/hero-mage.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-priest', path: 'res/hero-priest.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-rogue', path: 'res/hero-rogue.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-ranger', path: 'res/hero-ranger.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-paladin', path: 'res/hero-paladin.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-cleric', path: 'res/hero-cleric.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'hero-berserker', path: 'res/hero-berserker.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'sprite-sheet', key: 'npcs', path: 'res/npcs.png', options: { width: 16, height: 16, columns: 1, rows: 1, smooth: true } },
        { kind: 'image', key: 'battleBG', path: 'res/battle_backgrounds.png' },
        { kind: 'image', key: 'font', path: 'res/font_8x9.png' },
        { kind: 'json', key: 'enemies', path: 'res/enemies.json' },
        { kind: 'json', key: 'enemyTerritories', path: 'res/enemyTerritories.json' },
        { kind: 'json', key: 'assetClassCatalog', path: 'res/assetClassCatalog.json' },
        { kind: 'json', key: 'sourceSheetCatalog', path: 'res/assets/sourceSheetCatalog.json' },
        { kind: 'json', key: 'zoneCatalog72', path: 'res/zoneCatalog72.json' },
        { kind: 'json', key: 'zoneDataManifest72', path: 'res/zones/zoneDataManifest72.json' },
        { kind: 'canvas', key: 'enemiesImage', path: 'res/monsters.png' },
        { kind: 'json', key: 'enemyAtlas', path: 'res/enemyAtlas.json' },
        { kind: 'json', key: 'weaponSheetManifest', path: 'res/manifests/weapons-16x16.manifest.json' },
        { kind: 'json', key: 'armorSheetManifest', path: 'res/manifests/armor-16x16.manifest.json' },
        { kind: 'json', key: 'accessorySheetManifest', path: 'res/manifests/accessories-16x16.manifest.json' },
        { kind: 'json', key: 'worldSheetManifest', path: 'res/manifests/adventure-world-16x16.manifest.json' },
        { kind: 'json', key: 'tileset_tiles.json', path: 'res/maps/tileset_tiles.json' },
        { kind: 'json', key: 'enemy_territory_tiles.json', path: 'res/maps/enemy_territory_tiles.json' },
        { kind: 'json', key: 'collision_tiles.json', path: 'res/maps/collision_tiles.json' },
        { kind: 'json', key: 'overworld.json', path: 'res/maps/overworld.json' },
        { kind: 'json', key: 'equipment', path: 'res/equipment.json' },
        { kind: 'json', key: 'brecconary.json', path: 'res/maps/brecconary.json' },
        { kind: 'json', key: 'tantegelCastle.json', path: 'res/maps/tantegelCastle.json' },
        { kind: 'json', key: 'tantegelCastleUpstairs.json', path: 'res/maps/tantegelCastleUpstairs.json' },
        { kind: 'json', key: 'erdricksCave1.json', path: 'res/maps/erdricksCave1.json' },
        { kind: 'json', key: 'erdricksCave2.json', path: 'res/maps/erdricksCave2.json' },
        { kind: 'json', key: 'garinham.json', path: 'res/maps/garinham.json' },
        { kind: 'json', key: 'kol.json', path: 'res/maps/kol.json' },
        { kind: 'sound', key: 'MUSIC_TITLE_SCREEN', path: 'res/sound/01 Dragon Quest 1 - Intro ~ Overture (22khz mono).ogg' },
        { kind: 'sound', key: 'MUSIC_TANTEGEL', path: 'res/sound/02 Dragon Quest 1 - Tantegel Castle (22khz mono).ogg' },
        { kind: 'sound', key: 'MUSIC_TANTEGEL_LOWER', path: 'res/sound/03 Dragon Quest 1 - Tantegel Castle (Lower) (22khz mono).ogg' },
        { kind: 'sound', key: 'MUSIC_TOWN', path: 'res/sound/04 Dragon Quest 1 - Peaceful Village (22khz mono).ogg' },
        { kind: 'sound', key: 'MUSIC_OVERWORLD', path: 'res/sound/05 Dragon Quest 1 - Kingdom of Alefgard (22khz mono).ogg' },
        { kind: 'sound', key: 'MUSIC_BATTLE', path: 'res/sound/14 Dragon Quest 1 - A Monster Draws Near (16khz mono).ogg', options: { volume: 2.32 } },
        { kind: 'sound', key: 'MUSIC_DUNGEON_FLOOR_1', path: 'res/sound/06 Dragon Quest 1 - Dark Dungeon - Floor 1 (22khz mono).ogg' },
        { kind: 'sound', key: 'dead', path: 'res/sound/20 Dragon Quest 1 - Thou Hast Died (22khz mono).ogg' },
        { kind: 'sound', key: 'overnight', path: 'res/sound/21 Dragon Quest 1 - Special Item (22khz mono).ogg' },
        { kind: 'sound', key: 'victory', path: 'res/sound/25 Dragon Quest 1 - Victory (22khz mono).ogg', options: { loop: false, volume: 0 } },
        { kind: 'sound', key: 'stairs', path: 'res/sound/29 Dragon Quest 1 - Stairs Up (22khz mono).wav' },
        { kind: 'sound', key: 'run', path: 'res/sound/30 Dragon Quest 1 - Stairs Down (22khz mono).wav' },
        { kind: 'sound', key: 'menu', path: 'res/sound/32 Dragon Quest 1 - Menu Button (22khz mono).wav' },
        { kind: 'sound', key: 'confirmation', path: 'res/sound/33 Dragon Quest 1 - Confirmation (22khz mono).wav' },
        { kind: 'sound', key: 'hit', path: 'res/sound/34 Dragon Quest 1 - Hit (22khz mono).wav' },
        { kind: 'sound', key: 'excellentMove', path: 'res/sound/35 Dragon Quest 1 - Excellent Move (22khz mono).wav' },
        { kind: 'sound', key: 'attack', path: 'res/sound/36 Dragon Quest 1 - Attack (22khz mono).ogg' },
        { kind: 'sound', key: 'receiveDamage', path: 'res/sound/37 Dragon Quest 1 - Receive Damage (22khz mono).wav' },
        { kind: 'sound', key: 'prepareToAttack', path: 'res/sound/39 Dragon Quest 1 - Prepare to Attack (22khz mono).wav' },
        { kind: 'sound', key: 'missed1', path: 'res/sound/40 Dragon Quest 1 - Missed! (22khz mono).wav' },
        { kind: 'sound', key: 'missed2', path: 'res/sound/41 Dragon Quest 1 - Missed! (2) (22khz mono).wav' },
        { kind: 'sound', key: 'bump', path: 'res/sound/42 Dragon Quest 1 - Bumping into Walls (22khz mono).wav' },
        { kind: 'sound', key: 'castSpell', path: 'res/sound/43 Dragon Quest 1 - Cast A Spell (22khz mono).ogg' },
        { kind: 'sound', key: 'openChest', path: 'res/sound/44 Dragon Quest 1 - Open Treasure (22khz mono).ogg' },
        { kind: 'sound', key: 'door', path: 'res/sound/45 Dragon Quest 1 - Open Door (22khz mono).ogg' },
        { kind: 'sound', key: 'breatheFire', path: 'res/sound/46 Dragon Quest 1 - Breathe Fire (22khz mono).ogg' },
        { kind: 'sound', key: 'talk', path: 'res/sound/Dragon Warrior [Dragon Quest] SFX (1).wav' },
    ],
});
